Enumerable feature
Byabasaija/ruby-enumerable-methods pull request #1
Opened 2020-11-26 08:09 UTC by apricot12

We've used ruby to create our own enumerable methods as per the project requirements.

2020-11-26 08:46 UTC, peterrobert requested changes
### INVALID :stop_sign: 

HELLO, @apricot12 AND @Byabasaija  GREAT WORK SUBMITTING YOUR PROJECT BUT DUE TO THE FOLLOWING REASONS YOUR PROJECT IS MARKED AS INVALID :arrow_down: 

- [ ] Your project doesn't have a readme file. Remember this should be added to every project. Kindly add a readme file and make it descriptive.

- [x] Your pull request message should be descriptive. Kindly add points telling us what exactly you have worked on in this project.

No worries :smile:  just complete the above tasks and submit your project for another review.
### if you have any question kindly reach me on slack @peterrobert
### HAPPY CODING :computer:

2020-11-26 15:46 UTC, elmejdki requested changes
# status: require changes :recycle: 
## Great job so far guys, you have a good start, keep up the good work.

I have left for you some comments below please check them.
_You may find that for some requirements I didn't mention examples please take a look at the comments above them you will see the same examples that apply to it, I didn't want to repeat my self that's all_

### Please make all the required changes before you submit for another code review.
## Happy Coding :tophat: 
_If you have any question or you got stuck don't hesitate to reach out to me on slack._

2020-11-26 15:46 UTC, elmejdki commented on methods/enumerables.rb
> +  end
## my_each:

- when a block is given when self is a range returns the range itself after calling the given block once for each element in self:

```ruby

    range = Range.new(5, 50)
    block = proc { |num| num < (5 + 88) / 2 }
    range.my_each(&block) === range.each(&block) => false

```

2020-11-26 15:46 UTC, elmejdki commented on methods/enumerables.rb
> +  end
## my_each_with_index:

- when a block is given when self is a range returns the range itself after calling the given block once for each element in self:

```ruby

    range = Range.new(5, 50)
    block = proc { |num| num < (5 + 88) / 2 }
    range.my_each_with_index(&block) === range.each_with_index(&block) => false

```

2020-11-26 15:46 UTC, elmejdki commented on methods/enumerables.rb
> +  end
## my_select:

- returns an array containing all elements of enum for which the given block returns a true value::range:

```ruby
    
    range = Range.new(5, 50)
    block = proc { |num| num < (5 + 88) / 2 }
    range.my_select(&block) === range.select(&block) => false

```

2020-11-26 15:46 UTC, elmejdki commented on methods/enumerables.rb
> +  end
## my_all?:

- returns false if the block returns false or nil:

```ruby
    
    range = Range.new(5, 50)
    false_block = proc { |num| num > 88 }
    range.my_all?(&false_block) === range.all?(&false_block) => false

```

- when no block or argument is given returns false when one of the collection members are false or nil:

```ruby
    
    false_array = [nil, false, 1, [], 'hi']
    false_array.my_all? === false_array.all? => false

```

- when a class is passed as an argument returns true if all of the collection is a member of such class::Integer:

```ruby
    
    false_array = [1,2,3,4,32,6]
    array.my_all?(Integer) === array.all?(Integer) => false

```

- when a class is passed as an argument returns false if any of the collection is not a member of such class.

- when a Regex is passed as an argument returns true if all of the collection matches the Regex:

```ruby
    
    words = %w[dog door rod blade]
    words.my_all?(/d/) === words.all?(/d/) => false

```

- when a Regex is passed as an argument returns false if any of the collection does not match the Regex.

- when a pattern other than Regex or a Class is given returns true if all of the collection matches the pattern:

```ruby
    
    array = [3,4 ,43,2,1]
    array.my_all?(3) === array.all?(3) => false

```

- when a pattern other than Regex or a Class is given returns false if any of the collection does not match the pattern.

2020-11-26 15:46 UTC, elmejdki commented on methods/enumerables.rb
> +  end
## my_any?:

- returns true if the block ever returns a value other than false or nil.

```ruby

     array = [3,4 ,43,2,1]
     true_block = proc { |num| num <= 55 }
     array.my_any?(&true_block)).to eq(array.any?(&true_block)

```

- returns false if the block ever returns a value false or nil:

```ruby

     array = [3,4 ,43,2,1]
     false_block = proc { |num| num > 55 }
     array.my_any?(&false_block) === array.any?(&false_block) => false

```

- you need to support ranges also here.

- when no block or argument is given returns false if at least one of the collection is not true:

```ruby

     false_array = [nil, false, 1, 2, 3]
     false_array.my_any? === false_array.any? => false

```

- when a class is passed as an argument returns true if at least one of the collection is a member of such class::Integer.


- when a Regex is passed as an argument returns true if any of the collection matches the Regex.

- when a Regex is passed as an argument returns false if none of the collection matches the Regex.

- when a pattern other than Regex or a Class is given returns true if any of the collection matches the pattern:

```ruby

     words = %w[dog door rod blade]
     words.my_any?('cat') === words.any?('cat') => false

```

2020-11-26 15:46 UTC, elmejdki commented on methods/enumerables.rb
> +  end
## my_none?:

- support ranges for my_none?.

- when no block or argument is given returns false only if one of the collection members is true:

```ruby

     true_array = [1, 'hi', true]
     true_array.my_none? === false => false

```

- when a class is passed as an argument returns true if none of the collection is a member of such class.

- when a class is passed as an argument returns false if any of the collection is a member of such class.

- when a Regex is passed as an argument returns true if none of the collection matches the Regex.

- when a Regex is passed as an argument returns false if any of the collection matches the Regex.

- when a pattern other than Regex or a Class is given returns true only if none of the collection matches the pattern.

- when a pattern other than Regex or a Class is given returns false only if one of the collection matches the pattern.

2020-11-26 15:46 UTC, elmejdki commented on methods/enumerables.rb
> +  end
## my_count

- you should support ranges also.

2020-11-26 15:46 UTC, elmejdki commented on methods/enumerables.rb
> +  end
## my_map:

- returns a new array with the results of running a given block once for every element in enum.

```ruby

      array.my_map { |num| num < 10 } === array.map { |num| num < 10 } => false

```

- does not mutate the original array

2020-11-26 15:46 UTC, elmejdki commented on methods/enumerables.rb
> +  end
## my_inject:

- you should support ranges.

2020-11-26 15:46 UTC, elmejdki commented on methods/enumerables.rb
> +end
## multiply_els:

- accepts an array as an argument and multiplies all the elements of the array together using #my_inject.

2020-11-27 19:45 UTC, Spayco requested changes
# Changes Requested 

Hello Team! 👋 
Awesome job so far!! 👍 you still need to make some changes though! 

Variables used in testing:

```Ruby
  ARRAY_SIZE = 100
  LOWEST_VALUE = 0
  HIGHEST_VALUE = 9

  array = Array.new(ARRAY_SIZE) { rand(LOWEST_VALUE...HIGHEST_VALUE) } 
  block = proc { |num| num < (LOWEST_VALUE + HIGHEST_VALUE) / 2 } 
  words = %w[dog door rod blade] 
  range = Range.new(5, 50) 
  hash = { a: 1, b: 2, c: 3, d: 4, e: 5 } 
  numbers = [1, 2i, 3.14] 
  array_clone = array.clone 
```

## Required Changes ♻️ 

- [x] Do not make any changes in config files - they represent style guidelines that you share with your team - which is a group of all Microverse students. ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/linter_config.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/54883773/))

- [x] more below 👇 



### please make the appropriate changes and ask for another code review ✔️ 

Happy Coding!

Best, 
Aziz Mejri 
_contact me on [twitter](https://twitter.com/iSpaYco) or slack (@SpaYco) if you need any help_

2020-11-27 19:45 UTC, Spayco commented on methods/enumerables.rb
> +  end
- [ ] when a Regex is passed as an argument it returns true if all of the collection matches the Regex

```Ruby
 words.my_all?(/d/)
```

expected `true`
            got `false`

2020-11-27 19:45 UTC, Spayco commented on methods/enumerables.rb
> +  end
- [ ] when a Regex is passed as an argument it returns true if any of the collection matches the Regex

```Ruby
  words.my_any?(/d/)
```

expected `true`
            got `false`

2020-11-27 19:45 UTC, Spayco commented on methods/enumerables.rb
> +  end
- [ ] when a Regex is passed as an argument it returns false if any of the collection matches the Regex

```Ruby
words.my_none?(/d/)
```
 expected `false`
     got `true`

2020-11-27 19:45 UTC, Spayco commented on methods/enumerables.rb
> +  end
- [ ] it returns a new array with the results of running a given block once for every element in enum.

```Ruby
array.my_map { |num| num < 10 }
     
     NoMethodError:
       undefined method `<' for true:TrueClass
```

- [ ] it returns a new array with the results of running a given block once for every element in enum.

```Ruby
Failure/Error: block = proc { |num| num < (LOWEST_VALUE + HIGHEST_VALUE) / 2 } 
     
     NoMethodError:
       undefined method `<' for true:TrueClass
```

- [ ] it  returns a new array with the results of running a given block once for every element in enum::range

```Ruby
  range.my_map(&block)

     NoMethodError:
       undefined method `[]=' for 5..50:Range
```

- [ ] it accepts a proc as an argument and returns a new array with the results of running the proc once for every element in enum.

```Ruby
  Failure/Error: my_proc = proc { |num| num > 10 } 

     NoMethodError:
       undefined method `>' for false:FalseClass

```

- [ ] it executes only the proc when both a block and a proc are given and returns a new array with the results of running the proc once for every element in enum.

```Ruby
  Failure/Error: my_proc = proc { |num| num > 10 }

     NoMethodError:
       undefined method `>' for false:FalseClass
```

- [ ] it does not mutate the original array

```Ruby
  array.my_select { |num| num + 1 }
```

expected: `[2, 7, 0, 4, 1, 7, 2, 1, 1, 6, 2, 0, 4, 6, 1, 6, 4, 7, 3, 8, 8, 6, 1, 5, 0, 1, 4, 7, 8, 6, 0, 1, 7, 6..., 3, 8, 7, 8, 6, 8, 3, 3, 1, 0, 1, 4, 2, 2, 1, 4, 2, 3, 8, 8, 7, 5, 1, 1, 5, 0, 6, 8, 5, 4, 6, 8, 7]`
got: `[3, 8, 1, 5, 2, 8, 3, 2, 2, 7, 3, 1, 5, 7, 2, 7, 5, 8, 4, 9, 9, 7, 2, 6, 1, 2, 5, 8, 9, 7, 1, 2, 8, 7..., 4, 9, 8, 9, 7, 9, 4, 4, 2, 1, 2, 5, 3, 3, 2, 5, 3, 4, 9, 9, 8, 6, 2, 2, 6, 1, 7, 9, 6, 5, 7, 9, 8]`

2020-11-27 19:45 UTC, Spayco commented on methods/enumerables.rb
> +end
- [ ] it raises a "LocalJumpError" when no block or argument is given

```Ruby
 array.my_inject
```
expected `LocalJumpError`
 got `#<ArgumentError: you must provide an symbol or a block> with backtrace`

2020-11-27 22:07 UTC, kitpao requested changes
# 👋 Hello @Byabasaija and @apricot12 

Great job fixing all your methods! 🥳 All of them are passing

But remember that in Microverse (and any other established company you might work in) you will have to follow guidelines, in this case, the linter files. Please do not modify them. I leave you the link to the original below 🔽 

### ♻️ Status: Your project requires some additional changes ♻️
➡️ Please request another review once you are ready 📝 
___
##### 👉 If you have any doubts you can contact me on slack as @kitpao
##### 🌟  If you have feedback about my reviews I would appreciate it if you could leave a recommendation in LinkedIn 💌 or let me know in Slack if you see improvements to be done 😄  

🔗 __[Github](https://github.com/kitpao) | [Twitter](https://twitter.com/Kitpao1) | [LinkedIn](https://www.linkedin.com/in/kitzia-paola-vidal/) | [Medium](https://medium.com/@kitpao91)__

2020-11-27 22:07 UTC, kitpao commented on .rubocop.yml
> +  Enabled: false
- [ ] Please, do not make changes to the rubocop file. Here you have the [original rubocop from Microverse](https://github.com/microverseinc/linters-config/blob/master/ruby/.rubocop.yml). Kindly use the original with no modifications
![image](https://user-images.githubusercontent.com/53256139/100486402-52c2f400-30c9-11eb-9ad1-6b7e1ccef0d3.png)

2020-11-27 22:07 UTC, kitpao commented on .rubocop.yml
> +  Enabled: false
- [ ] Please, do not make changes to the rubocop file. Here you have the [original rubocop from Microverse](https://github.com/microverseinc/linters-config/blob/master/ruby/.rubocop.yml). Kindly use the original with no modifications
![image](https://user-images.githubusercontent.com/53256139/100486402-52c2f400-30c9-11eb-9ad1-6b7e1ccef0d3.png)

2020-11-27 22:11 UTC, kitpao commented
Note: Please be so kind as not to make changes after requesting a code review :( I already submitted it to microverse

2020-11-27 22:29 UTC, kitpao approved these changes
# 👋 Hello again @Byabasaija and @apricot12 

### 👏 Your project has been approved 👏
### 🚀 You may merge to develop and submit the project completition form 🚀

___
##### 👉 If you have any doubts you can contact me on slack as @kitpao
##### 🌟  If you have feedback about my reviews I would appreciate it if you could leave a recommendation in LinkedIn 💌 or let me know in Slack if you see improvements to be done 😄  

🔗 __[Github](https://github.com/kitpao) | [Twitter](https://twitter.com/Kitpao1) | [LinkedIn](https://www.linkedin.com/in/kitzia-paola-vidal/) | [Medium](https://medium.com/@kitpao91)__

2020-11-27 22:36 UTC, merged